### ISSUE TITLE
Consider introducing new rule "force-return-await` to achieve better stack traces

### ISSUE THREAD

**Issue by czlowiek488** [TheSoftwareHouse/express-boilerplate#32]
**Reason**
In node.js 10 the result of code below will be different than in node 8.
```ts
const sleep = delay => new Promise(resolve => setTimeout(resolve, delay));
const test1 = async (a = 0) => {
    await sleep(10);
    if(a < 10) return test1(a+1);
    else console.trace('noawait', a);
};
test1();
const test2 = async (a = 0) => {
    await sleep(10);
    if(a < 10) return await test2(a+1);
    else console.trace('await', a);
};
test2();
```
![119222214-7ce2f500-baf3-11eb-8cd5-03445f3a150a](https://user-images.githubusercontent.com/34620109/122422897-ceb15a80-cf8d-11eb-8c01-0ae941ca7c67.png)

**Description**
We should consider adding a custom rule which will force `return await` in functions.
However it isnt well optimized in node.js 12.
```
returnAwait: 1301.600ms
noReturnAwait: 1158.415ms
```
We should check how newer versions of node optimize it.

**Comment by sethii** [comment]
On Node 14 there is still a difference. So far I don't see a benefit from this additional stack traces. Let's talk about that internally, yet we're going to close this issue until then.
