### ISSUE TITLE
Node Prune does not work in new Macbook with M1 pro chip

### ISSUE THREAD

**Issue by nuttyroll** [TheSoftwareHouse/express-boilerplate#39]
executor failed running [/bin/sh -c apk add --no-cache bash curl git py-pip make &&   curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | sh &&   npm install node-dev -g && npm cache clean --force]: exit code: 1

This was the error I was getting. I changed the dockerfile to this 

RUN apk add --no-cache bash curl git py-pip make && \
  npm install node-dev -g && npm cache clean --force

RUN apk --no-cache add curl bash
RUN npx node-prune

to make it work

**Comment by sethii** [comment]
Thank you for info. We're going to fix it this week or maybe you want to do PR yourself, than feel free too :) The solution looks fine for me 👍

**Comment by sethii** [comment]
Fixed in new version
